### ISSUE TITLE
Bootstrap 4 & Font Awesome TreeView checkboxes do not work

### ISSUE THREAD

**Issue by srycroft** [atatanasov/gijgo#150] opened 2017-09-15 17:09 UTC
Using Bootstrap 4 and Font Awesome, the tree view checkboxes do not work. The boxes are there, but clicking does not check them.

Example: http://esdi.excelsystems.com/scripts/sdr/bootstrap4CheckboxesNotWorking.html

Changing to use Material Design icons also does not work - there is some graphic disruption/mismatch of some type.

**Comment by gabi85ro** [comment] 2017-09-29 13:52
I can confirm this, I'm having the same issue: the checkbox appear, but cannot select any of them. 
You can check by changing in http://gijgo.com/LiveEdit/Index/bootstrap-4-treeview.html?component=tree the `imageUrlField: 'flagUrl'` line to `checkboxes: true` and then click Run example.

Thank you,
Cosmin

**Comment by Rudedog9d** [comment] 2017-10-06 16:07
+1 on this. It looks like the fontawesome icons are messing it up.

I've found a work around, maybe the maintainers can do something useful with this:

```css
/* Set the checkbox icons manually via CSS */
    .gj-checkbox-material-icons input[type="checkbox"]:indeterminate + span:after {
      content: '\2796';
    }

    .gj-checkbox-material-icons input[type="checkbox"]:checked + span:after {
      content: '\2714';
    }
```
```html
<!-- Import a font, as v4 no longer has glypicons - we use open-iconic -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/open-iconic/1.1.1/font/css/open-iconic-bootstrap.min.css" />
```
```js
$('#tree').tree({
        uiLibrary: 'bootstrap4',
        // Set the Expand/Collapse Icons to something explicitly, instead of using fontawesome
        icons: {
          expand: '<span class="oi oi-chevron-right"></span>',
          collapse: '<span class="oi oi-chevron-bottom"></span>'
        },
        dataSource: '/api/v1/controls/tree',
        checkboxes: true
      });
```

Would be great to see a fix for this, instead of a hack like above.

**Comment by atatanasov** [comment] 2017-10-07 07:54
We are going to fix that in the new version. The new version is coming soon. stay tuned

**Closed** 2017-10-08 10:56 UTC
Labels: bug

**Comment by atatanasov** [comment] 2017-10-08 10:58
The fix is already avialable in the latest development build located at https://github.com/atatanasov/gijgo/tree/master/dist

**Comment by Rudedog9d** [comment] 2017-10-10 15:25
@atatanasov Would you consider adding support for custom `checkmark`/`indeterminate` icons, like the `expand`/`collapse` icons have? I tested the BS4 fix on master and it works, but we are not using `font-awesome` and don't want to include it just for two icons.
